name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Setup Meson build directory
        run: meson setup builddir --buildtype release

      - name: Build the project using Meson
        run: meson compile -C builddir -v

      - name: Install the project
        run: meson install -C builddir --strip --destdir ../install

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.os }}
          path: install/
